### ISSUE TITLE
Download Kinetics-400 

### ISSUE THREAD

**Issue by lovelyczli** [youngwanLEE/VoV3D#1]
Thanks for your great work! But I meet some problems when downloading Kinetics-400!

I am in China, and it is hard to get foreign website data. Even so, I attempt to download it by special tools. However, it still failed because downloading the dropbox link will be interrupted numerous times due to huge data, and it can not recover.

So could you please share another link for Kinetics-400? Many thanks!
Looking forward to your reply

**Comment by youngwanLEE** [comment]
@lovelyczli 
I'm sorry to say that I don't have another way to share the link except for dropbox.

**Comment by JiazeWang** [comment]
Thanks for your work and your kind help to down load the data. However, the link "http://dl.dropboxusercontent.com/s/zda3dfkp52eklvn/compress.tar.gz" is also expired. Could you please update the link?

**Comment by JJBOY** [comment]
If you update the link, please @me. Thanks for your sharing.

**Comment by sgao3** [comment]
I also got (Error 404) for the link above. Looking forward to the updated link. Thanks!

**Comment by youngwanLEE** [comment]
The dropbox link is pending until early February because of payment.

**Comment by JiazeWang** [comment]
> The dropbox link is pending until early February because of payment.

Thanks for your kind help, looking forward to your update!

**Comment by youngwanLEE** [comment]
@JiazeWang @JJBOY @sgao3 

The link was fixed. 

Now, you can download the dataset.
