### ISSUE TITLE
Different sampling rate use between X3D and VOV3D

### ISSUE THREAD

**Issue by ecr23xx** [youngwanLEE/VoV3D#2]
Thanks for your great work!

I notice that you use different sampling rate on SSv1 for [X3D-M](https://github.com/youngwanLEE/VoV3D/blob/a93dc3cd5694437cd0e7e34bd51af867ad3cf86f/configs/SSv1/x3d/x3d_M.yaml#L18-L19) (16x5) and [VOV3D-M](https://github.com/youngwanLEE/VoV3D/blob/a93dc3cd5694437cd0e7e34bd51af867ad3cf86f/configs/SSv1/vov3d/vov3d_M_F16.yaml#L19-L20) (16x8). Can you explain the reason why you make such modifications? Is that a typo, or it has something to do with the model?

**Comment by youngwanLEE** [comment]
@ecr23xx Hi,

Thanks for your interest in our work.

On the Something-Something dataset, we use a segment-based sampling strategy that splits each video into N segments and picks one frame to form a clip (N frames).

So, X3D-M and VoV3D-M use the same sampling rate.

You can investigate the details in L224-L238 the [datasets/ssv1.py](https://github.com/youngwanLEE/VoV3D/blob/main/vov3d/datasets/ssv1.py#L224-L238)


Meanwhile,
on Kinetics, both use 16x5 sampling rate.

**Comment by ecr23xx** [comment]
Thank you!
