### ISSUE TITLE
The number of validation videos in Kinetics

### ISSUE THREAD

**Issue by boy860521** [youngwanLEE/VoV3D#3]
Hi, huge thanks for providing the copy of the Kinetics-400 dataset!
However, when I unzip it, I got **19761** videos out of the validation folder instead of **19716**.
I wonder it might be a typo or my download bug out.

**Comment by youngwanLEE** [comment]
@boy860521 Hi,

the exact number of validation set is 19761, not 19716. 

That's a typo. sorry.

Please re-open this issue if you have another problem or issue.
