### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by hulianyuyy** [youngwanLEE/VoV3D#4]
Thanks for your great work! May i ask you how long did it takes for training VoV3D on Something-something v1 dataset from scratch (100 epochs, 8 GPUs)?

**Comment by youngwanLEE** [comment]
@hulianyuyy Hi,

For VoV3D-M-F16, it took 29 hours 24minutes on 8 V100 GPUs.

**Comment by youngwanLEE** [comment]
@hulianyuyy 
Please re-open this issue if you have more questions.
